### ISSUE TITLE
Error if @jspm/generator is in dependency tree

### ISSUE THREAD

**Issue by fusionstrings** [guybedford/chomp-extensions#24]
It's similar to https://github.com/jspm/generator/issues/147.

The error occurs when `@jspm/generator` is in dependency graph and built using chomp jspm extension.
`clearCache();` doesn't seem to work this time.

```sh
chomp build:error:html
  public/error.html invalidated
🞂 public/error.html
file:///Users/user/@jspm/jspm-generator-tests/node_modules/@jspm/generator/dist/generator-64b14857.js:1273
        throw new JspmError(`Unable to resolve package ${latestTarget.registry}:${latestTarget.name} to "${latestTarget.range}"${importedFrom(parentUrl)}`);
              ^

JspmError: Unable to resolve package npm:@babel/helpers to "^7.19.0" imported from https://ga.jspm.io/npm:@babel/core@7.19.0/lib/index.js
    at Resolver.resolveLatestTarget (file:///Users/user/@jspm/jspm-generator-tests/node_modules/@jspm/generator/dist/generator-64b14857.js:1273:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Installer.installTarget (file:///Users/user/@jspm/jspm-generator-tests/node_modules/@jspm/generator/dist/generator-64b14857.js:2179:24)
    at async TraceMap.resolve (file:///Users/user/@jspm/jspm-generator-tests/node_modules/@jspm/generator/dist/generator-64b14857.js:2606:27)
    at async TraceMap.visit (file:///Users/user/@jspm/jspm-generator-tests/node_modules/@jspm/generator/dist/generator-64b14857.js:2383:26)
    at async file:///Users/user/@jspm/jspm-generator-tests/node_modules/@jspm/generator/dist/generator-64b14857.js:2418:13
    at async Promise.all (index 13)
    at async TraceMap.visit (file:///Users/user/@jspm/jspm-generator-tests/node_modules/@jspm/generator/dist/generator-64b14857.js:2413:9)
    at async file:///Users/user/@jspm/jspm-generator-tests/node_modules/@jspm/generator/dist/generator-64b14857.js:2418:13
    at async Promise.all (index 6) {
  jspmError: true,
  code: undefined
}
x public/error.html [1.519082681s]
Unable to complete all tasks.
```

**Comment by guybedford** [comment]
Thanks for posting, this was due to a build backlog. The backlog should clear this weekend, but for now this was fixed with a manual rebuild.
